version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    working_directory: ~/app
    # executor:
    #   name: node/default
    steps:
      - checkout
      - attach_workspace:
          at: ~/app
      - run:
          name: Install node
          command: |
            npm install
            npm install react-scripts


      # - node/with-cache:
      #     steps:
      #       - run: rm -rf node_modules
      #       - run: rm -rf package-lock.json
      #       - run: 
      #       - run: npm install
      - run: 
          name: Eject application 
          command: echo y | npm run eject 
      - run:
          name: Test application 
          command: npm test 
workflows:
    build-and-test:
      jobs:
        - build-and-test