version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    working_directory: ~/app
    executor:
      name: node/default
    steps:
      - checkout
      - attach_workspace:
          at: ~/app
      - run:
          name: Install node
          command: |
            yarn install
      # - run:
      #     name: "JavaScript Linter"
      #     command: yarn lint --format junit -o reports/junit/js-lint-results.xml
      - run:
          name: "JavaScript Test Suite"
          environment:
            JEST_JUNIT_OUTPUT: reports/junit/js-test-results.xml
          command: |
            mkdir reports/junit/
            yarn test --ci --testResultsProcessor="jest-junit"
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit
      # - run:
      #     name: Test application 
      #     command: npm test
      # - run:
      #     name: Coverage report
      #     command: |
      #       npm run coverage
            

      # - run:
      #     command: ls
      # - store_artifacts:
      #     path: coverage
      #     destination: codeCoverage
      # - node/with-cache:
      #     steps:
      #       - run: rm -rf node_modules
      #       - run: rm -rf package-lock.json
      #       - run: 
      #       - run: npm install
      # - run: 
      #     name: Eject application 
      #     command: echo y | npm run eject 
       
workflows:
    build-and-test:
      jobs:
        - build-and-test