version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: rm -rf node_modules
            - run: rm -rf package-lock.json
            - run: npm install
      - run: 
          name: Eject application 
          command: echo y | npm run eject 
      - run:
          name: Test application 
          command: npm test 
workflows:
    build-and-test:
      jobs:
        - build-and-test